---
- hosts: all
  tasks:
    - name: add docker apt-key
      apt_key:
        keyserver: hkp://p80.pool.sks-keyservers.net:80
        state: present
        id: 58118E89F3A912897C070ADBF76221572C52609D
      become: true
      become_user: root
    - name: add repository
      apt_repository:
        repo: deb https://apt.dockerproject.org/repo ubuntu-xenial main
        state: present
      become: true
      become_user: root
    - name: install docker engine
      apt:
        update_cache: yes
        state: latest
        name: docker-engine
      become: true
      become_user: root
    - name: Upgrade latest pip, setuptools, docker-py and docker-compose with pip
      pip:
        name: "{{ item.name }}"
        state: latest
      with_items:
        - { name: pip, version: "latest", install: true }
        - { name: setuptools, version: "latest", install: true }
        - { name: docker-py, version: "lates", install: true }
        - { name: docker-compose, version: "1.9.0", install: true }
      when: (item.version=="latest" and item.install)
      become: true
      become_user: root
    - name: push code
      synchronize:
        src: ../../
        dest: /tmp/InstagramoBot
        recursive: yes
        archive: yes
    - name: build the image
      docker_image: >
        name=stasyatr/instagramobot
        tag=latest
        path=/tmp/InstagramoBot
        state=present
        force=yes
    - name: docker-compose up
      docker_service:
        build: yes
        restarted: true
        project_src: /tmp/InstagramoBot
    - name: remove source code
      file:
        path: /tmp/InstagramoBot
        state: absent
